name: "Deploy Heart Disease API to AWS"

on:
  push:
    branches: ["main"]

  jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-key-id: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-action/amazon-ecr-login@v1


      - name: Build, Tag and Push Image to ECR
        id: build-image
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registory}}
          ECR_REPOSITORY: 










          ]] 
